# Generated by Django 5.0.1 on 2024-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240713_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='content_3',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
