# Generated by Django 5.0.1 on 2024-10-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_1_post_content_2_post_content_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_for_content_1',
            field=models.ImageField(blank=True, null=True, upload_to='post/post-content1'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_for_content_2',
            field=models.ImageField(blank=True, null=True, upload_to='post/post-content2'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_for_content_3',
            field=models.ImageField(blank=True, null=True, upload_to='post/post-content3'),
        ),
    ]
