# Generated by Django 5.0.1 on 2024-10-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_text_for_content_1_post_text_for_content_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_for_content_1',
            new_name='img_for_content_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_for_content_2',
            new_name='img_for_content_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_for_content_3',
            new_name='img_for_content_3',
        ),
    ]
