# Generated by Django 5.0.1 on 2024-10-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_dop_text_post_end_title_post_text_1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_text_2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_text_3',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
