# Generated by Django 3.2.25 on 2024-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
