# Generated by Django 3.2.25 on 2024-07-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='tgCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/logo/')),
                ('img_in_detail_card', models.ImageField(blank=True, null=True, upload_to='uploads/img_Card/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('webLInkProject', models.CharField(blank=True, max_length=200, null=True)),
                ('header_1', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_1_2', models.TextField(blank=True, null=True)),
                ('paragraph_1_3', models.TextField(blank=True, null=True)),
                ('paragraph_1_4', models.TextField(blank=True, null=True)),
                ('paragraph_1_5', models.TextField(blank=True, null=True)),
                ('paragraph_1_6', models.TextField(blank=True, null=True)),
                ('inviteLink', models.CharField(blank=True, max_length=200, null=True)),
                ('header_2', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('paragraph_2_1', models.TextField(blank=True, null=True)),
                ('paragraph_2_2', models.TextField(blank=True, null=True)),
                ('paragraph_2_3', models.TextField(blank=True, null=True)),
                ('paragraph_2_4', models.TextField(blank=True, null=True)),
                ('paragraph_2_5', models.TextField(blank=True, null=True)),
                ('paragraph_2_6', models.TextField(blank=True, null=True)),
                ('header_3', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_3', models.TextField(blank=True, null=True)),
                ('paragraph_3_1', models.TextField(blank=True, null=True)),
                ('paragraph_3_2', models.TextField(blank=True, null=True)),
                ('paragraph_3_3', models.TextField(blank=True, null=True)),
                ('paragraph_3_4', models.TextField(blank=True, null=True)),
                ('paragraph_3_5', models.TextField(blank=True, null=True)),
                ('paragraph_3_6', models.TextField(blank=True, null=True)),
                ('header_4', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_4', models.TextField(blank=True, null=True)),
                ('paragraph_4_1', models.TextField(blank=True, null=True)),
                ('paragraph_4_2', models.TextField(blank=True, null=True)),
                ('paragraph_4_3', models.TextField(blank=True, null=True)),
                ('paragraph_4_4', models.TextField(blank=True, null=True)),
                ('paragraph_4_5', models.TextField(blank=True, null=True)),
                ('paragraph_4_6', models.TextField(blank=True, null=True)),
                ('header_5', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_5', models.TextField(blank=True, null=True)),
                ('paragraph_5_1', models.TextField(blank=True, null=True)),
                ('paragraph_5_2', models.TextField(blank=True, null=True)),
                ('paragraph_5_3', models.TextField(blank=True, null=True)),
                ('paragraph_5_4', models.TextField(blank=True, null=True)),
                ('paragraph_5_5', models.TextField(blank=True, null=True)),
                ('paragraph_5_6', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg.tgcategory')),
            ],
            options={
                'verbose_name': 'Монета',
                'verbose_name_plural': 'Монеты',
            },
        ),
    ]
