# Generated by Django 5.0.1 on 2024-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_7',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img_8',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/shop/product/'),
        ),
    ]
