# Generated by Django 5.0.1 on 2024-10-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesShop', '0002_product_product_img_2_product_product_img_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
